apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmd-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs/taylorw8
    server: 10.48.10.140
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmd-pvc    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-deployment
  labels:
    app: vmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmd
  template:
    metadata:
      labels:
        app: vmd
    spec:
      containers:
        - name: vmd
          image: cithit/vm-deploy:latest  
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfs       
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: vmd-pvc    
---
apiVersion: v1
kind: Service
metadata:
  name: vm-service
spec:
  type: LoadBalancer 
  loadBalancerIP: 10.43.90.160 #change this to match the load balancer ip                                  
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: flask

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  rules: 
  - host: 
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend: 
          service:
            name: vmd-service
            port:
              number: 5000
